# Generated by Django 4.1.3 on 2022-11-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_study", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "shirt_size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "db_table": "personchoice",
            },
        ),
        migrations.AlterModelTable(
            name="person",
            table="persons",
        ),
    ]
