# Generated by Django 4.1.3 on 2022-11-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("email", models.CharField(max_length=20)),
                ("local", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Man"), ("W", "Women")], max_length=1
                    ),
                ),
                ("age", models.IntegerField()),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
