# Generated by Django 4.1.3 on 2022-11-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Men"), ("W", "Wonmen")], max_length=1
                    ),
                ),
                ("generation", models.CharField(blank=True, default=" ", max_length=4)),
            ],
            options={
                "db_table": "accounts",
            },
        ),
    ]
