# Generated by Django 4.1.3 on 2022-11-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customquery_study", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Men"), ("W", "Wonmen")],
                default=" ",
                max_length=1,
            ),
        ),
    ]
