# Generated by Django 4.1.3 on 2022-11-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=10)),
                ("author", models.CharField(max_length=10)),
                ("price", models.IntegerField()),
            ],
            options={
                "db_table": "books",
            },
        ),
    ]
